generatorName: protobuf-schema
outputDir: protos/tools
inputSpec: build/processed-opensearch-openapi.yaml
templateDir: tools/proto-convert/src/config/protobuf-schema-template/
additionalProperties:
  addJsonNameAnnotation: true
  flattenComplexType: true
  numberedFieldNumberList: true
  startEnumsWithUnspecified: true
  aggregateModelsName: aggregated_models
inlineSchemaOptions:
  RESOLVE_INLINE_ENUMS: true
  SKIP_SCHEMA_REUSE: true
importMappings:
  google.protobuf.Struct: "google/protobuf/struct"
typeMappings:
  object: "google.protobuf.Struct"
  AnyType: "google.protobuf.Struct"
openapiGeneratorIgnoreList:
  - "README.md"
