generatorName: protobuf-schema
outputDir: protos/generated
inputSpec: build/processed-opensearch-openapi.yaml
templateDir: tools/proto-convert/src/config/protobuf-schema-template/
additionalProperties:
  packageName: org.opensearch.protobufs
  addJsonNameAnnotation: true
  flattenComplexType: true
  numberedFieldNumberList: true
  startEnumsWithUnspecified: true
  aggregateModelsName: aggregated_models
inlineSchemaOptions:
  RESOLVE_INLINE_ENUMS: true
  SKIP_SCHEMA_REUSE: true
importMappings:
  ObjectMap: "google/protobuf/struct"
typeMappings:
  object: "ObjectMap"
  AnyType: "ObjectMap"
openapiGeneratorIgnoreList:
  - "README.md"
