generatorName: protobuf-schema
outputDir: protos/generated
inputSpec: build/processed-opensearch-openapi.yaml
templateDir: tools/proto-convert/src/config/protobuf-schema-template/
additionalProperties:
  packageName: org.opensearch.protobufs
  addJsonNameAnnotation: false
  flattenComplexType: true
  numberedFieldNumberList: true
  startEnumsWithUnspecified: true
  aggregateModelsName: aggregated_models
  supportMultipleResponses: false
inlineSchemaOptions:
  RESOLVE_INLINE_ENUMS: true
  SKIP_SCHEMA_REUSE: true
typeMappings:
  object: "ObjectMap"
  AnyType: "ObjectMap"
  number: "GeneralNumber"
  bytes: "bytes"
  NullValue: "NullValue"
openapiGeneratorIgnoreList:
  - "README.md"
