# Target API paths to include in proto generation
# Format:
#   path:
#     x-operation-group:    # optional, list of operation groups to include
#       - group1
#       - group2
# If x-operation-group is not specified, all operations on that path are included
paths:
  /{index}/_bulk:
    x-operation-group:
    - bulk
  /{index}/_search:
    x-operation-group:
    - search

# Schemas to exclude from proto generation
# These schemas and their nested dependencies will not be included
excluded_schemas:
  - AggregationContainer
  - Aggregate
  - Suggester
  - Suggest
  - BoostingQuery
  - DisMaxQuery
  - QueryStringQuery
  - SimpleQueryStringQuery
  - IntervalsQuery
  - ScriptScoreQuery
  - CommonTermsQuery
  - CombinedFieldsQuery
  - DistanceFeatureQuery
  - GeoPolygonQuery
  - GeoShapeQuery
  - HasChildQuery
  - HasParentQuery
  - MoreLikeThisQuery
  - NeuralQuery
  - ParentIdQuery
  - PercolateQuery
  - RankFeatureQuery
  - SpanContainingQuery
  - SpanFieldMaskingQuery
  - SpanFirstQuery
  - SpanMultiTermQuery
  - SpanNearQuery
  - SpanNotQuery
  - SpanOrQuery
  - SpanTermQuery
  - SpanWithinQuery
  - ObjectMap
  - TypeQuery
  - WrapperQuery
  - XyShapeQuery
